version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: 'securly-data-fetcher:latest'
    build:
      context: .
    container_name: securly-data-fetcher
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - CANVAS_INSTANCE_URL=XXXXXXXXXXXXXX
      - CANVAS_CLIENT_ID=YYYYYYYYYY
      - CANVAS_SECRET_KEY=ZZZZZZZZZ
volumes:
  db:
    driver: local